name: Build
on:
  push:
  pull_request:
  create:
    tags:
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: 2f
            asset_name: 2f-x86_64-linux
          - os: macos-latest
            artifact_name: 2f
            asset_name: 2f-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: 2f.exe
            asset_name: 2f-x86_64-windows.exe
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - uses: actions/checkout@v3
    - name: Dependencies
      run: go get -t -d ./...
    - name: Build
      run: go build -trimpath
    - name: Release
      uses: svenstaro/upload-release-action@2.5.0
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        overwrite: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.event.ref }}
